#!/usr/bin/ruby

puts "Welcome to the Fibbonacci Sequence.\n"
puts "How many iterations of the sequence would you like to see?\n"



def fib_sequence ( iterations )
	i = 0
	j = 0
	oldnumber = 0
	nextnumber = 1
	iterations.times { puts "Iteration number #{j} number is #{nextnumber}"
        oldnumber = i 
	i = nextnumber
	nextnumber += oldnumber   
	 j += 1 }
end
number = gets
fib_sequence(number.to_i + 1)


